### ISSUE TITLE
Why are divid audio into small chunks 

### ISSUE THREAD

**Issue by adityajain407** [kaloprojects/KALO-ESP32-Voice-Assistant#3]
Insane project kalo,
But you let me know why we divide audio in chunks which uploading to server

    const size_t bufferSize = 1024; // best values seem anywhere between 1024 and 2048;

**Comment by adityajain407** [comment]
What if increase the size of chunks to 16kb

**Comment by kaloprojects** [comment]
Not working, try it ;)

**Comment by adityajain407** [comment]
Okay I also test it out,thank you so much :)

**Comment by adityajain407** [comment]
Thanks
